=== uscope-platform/fCore_toolchain/includes/schemas/v2/emulator/emulator_spec_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "Root Schema",
  "required": [
    "version",
    "cores",
    "interconnect",
    "emulation_time",
    "deployment_mode"
  ],


  "properties": {
    "version":{
      "type": "integer",
      "title": "input file schema version"
    },
    "cores": {"$ref": "cores_schema.json"},
    "interconnect": {"$ref": "interconnect_schema.json"},
    "emulation_time": {
      "type": "number",
      "title": "Length of time to emulation_phase"
    },
    "deployment_mode": {
      "type": "boolean",
      "title": "Enable custom image deployment mode"
    }
  }
}

=== uscope-platform/fCore_toolchain/test/schemas/valid_emulator_schema.json
{
  "version": 2,
  "cores": [
    {
      "id": "test_producer",
      "inputs": [
        {
          "name": "input_1",
          "metadata": {
            "type": "float",
            "width": 32,
            "signed": false,
            "common_io": false
          },
          "is_vector": false,
          "vector_size": 1,
          "source": {
            "type":"series",
            "value": [15.7,67.4]
          },
          "channel": 0
        },
        {
          "name": "input_2",
          "metadata": {
            "type": "float",
            "width": 32,
            "signed": false,
            "common_io": false
          },
          "is_vector": false,
          "vector_size": 1,
          "source": {
            "type":"series",
            "value":[42.92, -5.8]
          },
          "channel": 0
        }
      ],
      "order": 0,
      "outputs": [
      ],
      "program":{
        "content": "void main(){float input_1,input_2; float c = input_1 + input_2; float producer_out = producer_out + c;}",
        "build_settings": {
          "io": {
            "inputs": [
              "input_1",
              "input_2"
            ],
            "outputs": [
            ],
            "memories": [
              "producer_out"
            ]
          }
        },
        "headers": []
      },
      "memory_init": [
        {
          "name": "producer_out",
          "metadata": {
            "type": "float",
            "width": 32,
            "signed": false,
            "common_io": false
          },
          "is_vector": false,
          "vector_size": 1,
          "is_output": true,
          "reg_n": 4,
          "value": 0
        }
      ],
      "options":{
        "comparators":"reducing",
        "efi_implementation":"efi_sort"
      },
      "channels":1,
      "sampling_frequency": 1,
      "deployment": {
        "has_reciprocal": false,
        "control_address": 18316525568,
        "rom_address": 17179869184
      }
    },
    {
      "id": "test_consumer",
      "inputs": [],
      "memory_init": [],
      "input_data": [],
      "outputs": [
        {
          "metadata": {
            "type": "integer",
            "width": 32,
            "signed": true,
            "common_io": false
          },
          "is_vector": false,
          "vector_size": 1,
          "name":"consumer_out"
        }
      ],
      "order": 1,
      "program":{
        "content": "void main(){float input_1; float consumer_out = input_1;}",
        "build_settings": {
          "io": {
            "inputs": [
              "input_1"
            ],
            "outputs": [
              "consumer_out"
            ],
            "memories": [
            ]
          }
        },
        "headers": []
      },
      "options":{
        "comparators":"reducing",
        "efi_implementation":"efi_sort"
      },
      "channels":1,
      "sampling_frequency": 1,
      "deployment": {
        "has_reciprocal": false,
        "control_address": 18316525568,
        "rom_address": 17179869184
      }
    }
  ],
  "interconnect":[
    {
      "source":"test_producer",
      "destination":"test_consumer",
      "ports":[
        {
          "source": "test_producer.test_out",
          "destination": "test_consumer.input_1"
        }
      ]
    }
  ],
  "emulation_time": 2,
  "deployment_mode": false
}

=== uscope-platform/fCore_toolchain/test/schemas/msgpackd_schema.json
{
  "version": 2,
  "cores": [
    {
      "channels":1,
      "deployment":{
        "control_address":18316525568.0,
        "has_reciprocal":false,
        "rom_address":17179869184.0
      },
      "id":"test",
      "input_data":[],
      "inputs":[],
      "memory_init":[
        {
          "is_output":true,
          "metadata":{
            "signed":true,
            "type":"float",
            "width":32
          },
          "name":"mem",
          "is_vector": false,
          "vector_size": 1,
          "reg_n":4,
          "value":14
        },
        {
          "is_output":true,
          "metadata":{
            "signed":true,
            "type":"integer",
            "width":16
          },
          "is_vector": false,
          "vector_size": 1,
          "name":"mem_2",
          "reg_n":3,
          "value":12
        }
      ],
      "options":{
        "comparators":"reducing",
        "efi_implementation":"none"
      },
      "order":0,
      "outputs":[
        {
          "metadata":{
            "signed":true,
            "type":"float",
            "width":32,
            "common_io": false
          },
          "name":"out",
          "is_vector": false,
          "vector_size": 1
        }
      ],
      "program":{
        "build_settings":{
          "io":{
            "inputs":[],
            "memories":["mem","mem_2"],
            "outputs":["out"]
          }
        },
        "content":"int main(){float mem;float mem_2;float out = mem + mem_2;}",
        "headers":[]
      },
      "sampling_frequency":1
    }
  ],
  "deployment_mode":false,
  "emulation_time":2,
  "interconnect":[]
}

=== uscope-platform/fCore_toolchain/test/emulator_files/test_compilation_memory.json
{
  "version": 2,
  "cores": [
    {
      "id": "test",
      "inputs": [
        {
          "name": "input_1",
          "metadata": {
            "type": "float",
            "width": 32,
            "signed": false,
            "common_io": false
          },
          "source": {
            "type":"series",
            "value": [15.7, 67.4]
          }
        }
      ],
      "outputs": [
        {
          "type": "float",
          "metadata": {
            "type": "float",
            "width": 32,
            "signed": false
          },
          "name":"out"
        }
      ],
      "memory_init": [],
      "program":{
        "content": "int main(){float input_1; float mem; float out; mem = mem + input_1; out = mem;}",
        "build_settings": {
          "io": {
            "inputs": [
              "input_1"
            ],
            "memories": [
              "mem"
            ],
            "outputs": [
              "out"
            ]
          }
        },
        "headers": []
      },
      "order": 1,
      "options":{
        "comparators":"reducing",
        "efi_implementation":"efi_sort"
      },
      "channels":1,
      "sampling_frequency": 1,
      "deployment": {
        "has_reciprocal": false,
        "control_address": 18316525568,
        "rom_address": 17179869184
      }
    }
  ],
  "interconnect": [],
  "emulation_time": 2,
  "deployment_mode": false
}
